/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssetCategory = IDL.Variant({
  'fonts' : IDL.Null,
  'audio' : IDL.Null,
  'shaders' : IDL.Null,
  'sprites' : IDL.Null,
  'tilemaps' : IDL.Null,
  'models' : IDL.Null,
});
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'uploaderName' : IDL.Text,
  'previewUrl' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'fileSize' : IDL.Text,
  'blobId' : IDL.Opt(IDL.Text),
  'category' : AssetCategory,
  'downloadCount' : IDL.Nat,
  'engineTags' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAsset' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        AssetCategory,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'getAssetById' : IDL.Func([IDL.Nat], [IDL.Opt(Asset)], ['query']),
  'getAssetsByCategory' : IDL.Func(
      [AssetCategory],
      [IDL.Vec(Asset)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'incrementAssetDownloadCount' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssetCategory = IDL.Variant({
    'fonts' : IDL.Null,
    'audio' : IDL.Null,
    'shaders' : IDL.Null,
    'sprites' : IDL.Null,
    'tilemaps' : IDL.Null,
    'models' : IDL.Null,
  });
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'uploaderName' : IDL.Text,
    'previewUrl' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'fileSize' : IDL.Text,
    'blobId' : IDL.Opt(IDL.Text),
    'category' : AssetCategory,
    'downloadCount' : IDL.Nat,
    'engineTags' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAsset' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          AssetCategory,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'getAssetById' : IDL.Func([IDL.Nat], [IDL.Opt(Asset)], ['query']),
    'getAssetsByCategory' : IDL.Func(
        [AssetCategory],
        [IDL.Vec(Asset)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'incrementAssetDownloadCount' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };